server:
  port: 5000

spring:
  application:
    name: POS-APP
  datasource:
    username: root
    password: 7qvt6t2738
    url: jdbc:mysql://localhost:3306/dbpos
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
